// Generated by CoffeeScript 2.5.1
(function() {
  var debugmodule;

  debugmodule = {
    name: "debugmodule"
  };

  //#############################################################################
  debugmodule.initialize = function() {};

  
  //#############################################################################
  // console.log "debugmodule.initialize - nothing to do"
  debugmodule.modulesToDebug = {
    unbreaker: true
  };

  // cliargumentsmodule: true
  // cloudservicemodule: true
  // configmodule: true
  // constructionmodule: true
  // createprocessmodule: true
  // encryptionmodule: true
  // githubservicemodule: true
  // gitlabservicemodule: true
  // gitmodule: true
  // globalscopemodule: true
  // pathhandlermodule: true
  // recipemodule: true
  // remotehandlermodule: true
  // startupmodule: true
  // thingymodule: true
  // transformationmodule: true
  // urlhandlermodule: true
  // useractionmodule: true
  // userconfigmodule: true
  // userinquirermodule: true
  module.exports = debugmodule;

}).call(this);
