// Generated by CoffeeScript 2.5.1
(function() {
  var git, gitmodule, globalScope, log;

  gitmodule = {
    name: "gitmodule"
  };

  //region modulesFromEnvironment
  //region node_modules
  git = require("simple-git/promise");

  //endregion

  //region localModules
  globalScope = null;

  //endregion
  //endregion

  //region logPrintFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["gitmodule"] != null) {
      console.log("[gitmodule]: " + arg);
    }
  };

  //endregion
  //#############################################################################
  gitmodule.initialize = function() {
    log("gitmodule.initialize");
    globalScope = allModules.globalscopemodule;
  };

  
  //region exposedFunctions
  gitmodule.addSubmodule = async function(base, remote, label) {
    var url;
    log("gitmodule.addSubmodule");
    url = remote.getSSH();
    if (!url || !globalScope.repoIsInScope(remote.getRepo())) {
      url = remote.getHTTPS();
    }
    await git(base).submoduleAdd(url, label);
  };

  gitmodule.push = async function(base) {
    log("gitmodule.push");
    await git(base).push("origin", "master");
  };

  gitmodule.addAll = async function(base) {
    log("gitmodule.addAll");
    await git(base).add(".");
  };

  gitmodule.add = async function(base, path) {
    var result;
    log("gitmodule.addAll");
    result = (await git(base).add(path));
    return result;
  };

  gitmodule.commit = async function(base, message) {
    var result;
    log("gitmodule.commit");
    result = (await git(base).commit(message));
    return result;
  };

  gitmodule.init = async function(base, remote) {
    log("gitmodule.init");
    await git(base).init();
    await git(base).addRemote("origin", remote.getSSH());
  };

  gitmodule.addPush = async function(base, remote) {
    log("gitmodule.addPush");
    await gitmodule.addAll(base);
    await git(base).commit("initial commit");
    await gitmodule.push(base);
  };

  gitmodule.initPush = async function(base, remote) {
    log("gitmodule.initAndPush");
    await gitmodule.init(base, remote);
    await gitmodule.addAll(base);
    await git(base).commit("initial commit");
    await gitmodule.push(base);
  };

  gitmodule.clone = async function(remote, base) {
    var url;
    log("gitmodule.clone");
    url = remote.getSSH();
    if (!url || !globalScope.repoIsInScope(remote.getRepo())) {
      url = remote.getHTTPS();
    }
    if (!url) {
      throw "No URL to clone available for RemoteObject!";
    }
    await git(base).clone(url);
  };

  gitmodule.stash = async function(base) {
    var result;
    log("gitmodule.stash");
    result = (await git(base).stash());
    return result;
  };

  gitmodule.stashPop = async function(base) {
    var result;
    log("gitmodule.stashPop");
    result = (await git(base).stash(["pop"]));
    return result;
  };

  gitmodule.restoreStaged = async function(base, path) {
    var result;
    log("gitmodule.restoreStaged");
    result = (await git(base).raw(['restore', '--staged', path]));
    return result;
  };

  gitmodule.deinitSubmodule = async function(base, modulePath) {
    var result;
    log("gitmodule.deinitSubmodule");
    result = (await git(base).raw(['submodule', 'deinit', '-f', '--', modulePath]));
    return result;
  };

  gitmodule.rmCached = async function(base, path) {
    var result;
    log("gitmodule.rmCached");
    result = (await git(base).raw(['rm', '--cached', '-r', path]));
    return result;
  };

  gitmodule.getGitRoot = async function(base) {
    var result;
    log("gitmodule.getGitRoot");
    result = (await git(base).raw(['rev-parse', '--show-toplevel']));
    return result;
  };

  gitmodule.getOriginURL = async function(base) {
    var result;
    log("gitmodule.getOriginURL");
    result = (await git(base).raw(['config', '--get', 'remote.origin.url']));
    return result;
  };

  //endregion
  module.exports = gitmodule;

}).call(this);
