// Generated by CoffeeScript 2.5.1
(function() {
  var CLI, Spinner, c, cfg, checkDirectoryExists, checkDirectoryIsInGit, checkSomethingExists, exec, execGitCheckPromise, fs, git, homedir, inquirer, log, os, pathModule, pathhandlermodule, prepareUserConfigPath, print, resolveHomeDir, thingyName, urlHandler, utl;

  pathhandlermodule = {
    name: "pathhandlermodule"
  };

  //region modulesFromEnvironment
  //region node_modules
  inquirer = require("inquirer");

  git = require("simple-git");

  c = require('chalk');

  CLI = require('clui');

  Spinner = CLI.Spinner;

  fs = require("fs-extra");

  pathModule = require("path");

  os = require("os");

  exec = require("child_process").exec;

  //endregion

  //region localModules
  utl = null;

  cfg = null;

  git = null;

  urlHandler = null;

  //endregion
  //endregion

  //region logPrintFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["pathhandlermodule"] != null) {
      console.log("[pathhandlermodule]: " + arg);
    }
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion
  //#############################################################################
  pathhandlermodule.initialize = async function() {
    log("pathhandlermodule.initialize");
    utl = allModules.utilmodule;
    cfg = allModules.configmodule;
    git = allModules.gitmodule;
    urlHandler = allModules.urlhandlermodule;
    await prepareUserConfigPath();
  };

  //region internalProperties
  homedir = os.homedir();

  thingyName = "";

  //endregion

  //region internalFunctions
  execGitCheckPromise = function(path) {
    var options;
    options = {
      cwd: path
    };
    return new Promise(function(resolve, reject) {
      var callback;
      callback = function(error, stdout, stderr) {
        if (error) {
          reject(error);
        }
        if (stderr) {
          reject(new Error(stderr));
        }
        return resolve(stdout);
      };
      return exec("git rev-parse --is-inside-work-tree", options, callback);
    });
  };

  prepareUserConfigPath = async function() {
    var dirPath, filePath;
    log("prepareUserConfigPath");
    filePath = resolveHomeDir(cfg.cli.userConfigPath);
    dirPath = pathModule.dirname(filePath);
    await fs.mkdirp(dirPath);
    pathhandlermodule.userConfigPath = filePath;
  };

  resolveHomeDir = function(path) {
    log("resolveHomeDir");
    if (!path) {
      return;
    }
    if (path[0] === "~") {
      path = path.replace("~", homedir);
    }
    return path;
  };

  checkSomethingExists = async function(something) {
    var err;
    try {
      await fs.lstat(something);
      return true;
    } catch (error1) {
      err = error1;
      return false;
    }
  };

  checkDirectoryExists = async function(path) {
    var err, stats;
    try {
      stats = (await fs.lstat(path));
      return stats.isDirectory();
    } catch (error1) {
      err = error1;
      // console.log(c.red(err.message))
      return false;
    }
  };

  checkDirectoryIsInGit = async function(path) {
    var err;
    try {
      await execGitCheckPromise(path);
      return true;
    } catch (error1) {
      err = error1;
      // console.log(c.red(err.message))
      return false;
    }
  };

  //endregion

  //region exposed
  //region exposedProperties
  pathhandlermodule.homedir = homedir; //directory

  pathhandlermodule.userConfigPath = ""; //file

  pathhandlermodule.basePath = ""; //directory

  pathhandlermodule.thingyModuleBase = ""; //direcotry

  pathhandlermodule.parentPath = ""; //directory

  pathhandlermodule.thingyPath = ""; //directory

  pathhandlermodule.temporaryFilesPath = ""; //directory

  pathhandlermodule.recipesPath = ""; //directory

  //endregion

  //region exposedFunctions
  pathhandlermodule.getParentThingyName = async function() {
    var base, url;
    log("pathhandlermodule.getThingyName");
    base = pathhandlermodule.thingyModuleBase;
    pathhandlermodule.parentPath = (await git.getGitRoot(base));
    pathhandlermodule.parentPath = pathhandlermodule.parentPath.replace(/\s/g, "");
    url = (await git.getOriginURL(base));
    url = url.replace(/\s/g, "");
    return urlHandler.getRepo(url);
  };

  pathhandlermodule.prepare = async function() {
    var basePath, exists;
    log("pathhandlermodule.checkBase");
    basePath = resolveHomeDir(cfg.userConfig.defaultThingyRoot);
    if (!pathModule.isAbsolute(basePath)) {
      throw "unexpected path in userConfig: " + basePath;
    }
    pathhandlermodule.basePath = basePath;
    exists = (await checkDirectoryExists(pathhandlermodule.basePath));
    if (!exists) {
      throw new Error("Our basePath (" + basePath + ") does not exist!");
    }
    pathhandlermodule.thingyModuleBase = process.cwd();
  };

  pathhandlermodule.prepareTemporaryFilesPath = function() {
    log("pathhandlermodule.prepareTemporaryFilesPath");
    pathhandlermodule.temporaryFilesPath = resolveHomeDir(cfg.userConfig.temporaryFiles);
  };

  pathhandlermodule.prepareRecipesPath = function() {
    log("pathhandlermodule.prepareRecipesPath");
    if (!cfg.userConfig.recipesPath) {
      cfg.userConfig.recipesPath = "~/.config/thingyBubble/recipes";
    }
    pathhandlermodule.recipesPath = resolveHomeDir(cfg.userConfig.recipesPath);
  };

  pathhandlermodule.ensureDirectoryExists = async function(directory) {
    var result;
    log("pathhandlermodule.ensureDirectoryExists");
    directory = resolveHomeDir(directory);
    result = (await fs.mkdirp(directory));
  };

  pathhandlermodule.somethingExistsAtBase = async function(name) {
    var something;
    something = pathModule.resolve(pathhandlermodule.basePath, name);
    return (await checkSomethingExists(something));
  };

  pathhandlermodule.directoryExistsAtBase = async function(dirName) {
    var dirPath;
    dirPath = pathModule.resolve(pathhandlermodule.basePath, dirName);
    return (await checkDirectoryExists(dirPath));
  };

  pathhandlermodule.directoryExists = async function(dir) {
    log("pathhandlermodule.direcotryExists");
    return (await checkDirectoryExists(dir));
  };

  pathhandlermodule.resolve = pathModule.resolve;

  pathhandlermodule.relative = pathModule.relative;

  //endregion
  //endregion
  module.exports = pathhandlermodule;

}).call(this);
